name: mc-publish
on:
  workflow_dispatch:
jobs:
  build:
    # ...
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          #modrinth-id: of19plFw
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 1038550
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
